### ISSUE TITLE
Bar graphs should start at 2009

### ISSUE THREAD

**Issue by cfarm** [cfpb/consumer-credit-trends#25]
Many bar graphs start at January 2008 instead of January 2009.

![screen shot 2016-12-12 at 10 27 43 pm](https://cloud.githubusercontent.com/assets/702526/21126461/476bf5e4-c0ba-11e6-802e-bc7396bd47e5.png)

**Comment by mistergone** [comment]
There was a typo in the code regulating this. It'll be fixed in my next PR!
