### ISSUE TITLE
Credit card charts use the term "loans"

### ISSUE THREAD

**Issue by marteki** [cfpb/consumer-credit-trends#36]
The credit card charts use the term "loans," rather than "credit cards".

## Current behavior

- Headings of 'Number of loans originated', etc.

## Expected behavior

- Headings of 'Number of credit cards originated', etc.

## Steps to replicate behavior (include URLs)

1. `./setup.sh`, `gulp watch`, and then look at any credit card graph or map

## Screenshots

 For http://localhost:3000/charts/credit-cards/origination-activity/figure-1a__number__credit-cards.html:

![screen shot 2016-12-13 at 8 41 57 pm](https://cloud.githubusercontent.com/assets/1183435/21166638/aaa08098-c174-11e6-8505-a289daaad954.png)

**Comment by cfarm** [comment]
I can fix this! nice catch.

**Comment by marteki** [comment]
Addressed in #38. Nice!
