### ISSUE TITLE
Deep subprime credit cards line charts axis has duplicate tick lines

### ISSUE THREAD

**Issue by cfarm** [cfpb/consumer-credit-trends#41]
![image](https://cloud.githubusercontent.com/assets/702526/21207097/18441154-c234-11e6-86ae-10ad7384f082.png)

> Decimal billions are appearing incorrectly. All the horizontal lines below the top line are appearing twice on the chart, which makes it hard to know what the graph is showing.

Here's the [local site link](http://localhost:3000/charts/credit-cards/borrower-risk-profiles/figure-2a__deep-subprime__credit-cards.html) and the [github pages](https://cfarm.github.io/consumer-credit-trends/charts/credit-cards/borrower-risk-profiles/figure-2a__deep-subprime__credit-cards.html) link

**Comment by marteki** [comment]
It's also happening on the "65 and older" lending by borrower age chart for student loans:

![screen shot 2016-12-14 at 7 40 13 pm](https://cloud.githubusercontent.com/assets/1183435/21207730/d4237d12-c237-11e6-83cb-1664b63658b0.png)

These seem to be the only charts which currently have a top value that is less than 1.0 billion.

**Comment by cfarm** [comment]
Only other example @marteki found:

https://cfarm.github.io/consumer-credit-trends/charts/student-loans/borrower-age/figure-4a__65-and-older__student-loans/.html

![image](https://cloud.githubusercontent.com/assets/702526/21207799/4355a11a-c238-11e6-870f-37b1ff1231ca.png)

**Comment by marteki** [comment]
Idea for a possible cause (suggested by @hillaryj, who is the person who originally found the duplicate tick lines problem):

Maybe it's trying to show 0, 0.05B, 0.1B, 0.15B, etc but is being capped at one decimal place?

**Comment by mistergone** [comment]
@marteki - Exactly. It's cutting the string too short.

I have a fix for this already in my next revision to `cfpb-chart-builder` so I can get version 0.0.9 out to fix this.

**Comment by mistergone** [comment]
Fixed here: https://github.com/cfpb/cfpb-chart-builder/pull/9

__EDIT:__ And `cfpb-chart-builder` is updated here: #42
